---
- name: Install dockutil from patch
  raw: |
    DLURL=$(curl --silent "https://api.github.com/repos/kcrawford/dockutil/releases/latest" | jq -r '.assets[].browser_download_url' | grep pkg)
    curl -sL ${DLURL} -o /tmp/dockutil.pkg
    sudo installer -pkg "/tmp/dockutil.pkg" -target /
    rm /tmp/dockutil.pkg
- name: Dock setup
  include_role:
    name: gordian_jklapacz.mac.dock
