---
- name: check if .zprofile exists
  stat:
    path: "{{ zprofile_path }}"
  register: zprofile_st

- name: create .zprofile
  file:
    path: "{{ zprofile_path }}"
    state: touch
  when: not zprofile_st.stat.exists

- blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK brew-path"
    path: "{{ zprofile_path }}"
    block: |
      export PATH="{{ homebrew_extra_paths | join(":") }}"

- name: setup pyenv+python
  include_role:
    name: markosamuli.pyenv
  when: configure_python

- name: python-specific environment variables
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK python-specific-environments"
    path: "{{ zprofile_path }}"
    block: |
      export LDFLAGS="{{ homebrew_lib | join(" ") }}"
      export CPPFLAGS="{{ homebrew_include | join(" ") }}"
      export OPENBLAS="{{ homebrew_openblas }}"
      export MACOSX_DEPLOYMENT_TARGET={{ macosx_deployment_target }}

